### ISSUE TITLE
ch28/MethodSwizzle project crashes under Xcode 4.5 DP4

### ISSUE THREAD

**Issue by jaythrash** [iosptl/ios6ptl#1]
Under Xcode 4.5 DP4, the MethodSwizzle project is crashing on 

NSNotificationCenter+RNSwizzle.m:line 27 where it's trying to call the original version of addObserver:

**Comment by rnapier** [comment]
Confirmed. Will investigate during Ch28 AR.

**Comment by rnapier** [comment]
Fixed.
